### ISSUE TITLE
Crashes when typing in same struct name as field member

### ISSUE THREAD

**Issue by praydog** [cursey/regenny#11]
Had this happen sometimes.

Take the following example:
```c
enum FooEnum : uint32_t {
    Baz = 0
};

struct Foo 0x1000 {
    int blah;
    int foo_enum_before_i_found_the_enum;
};
```

Upon trying to insert FooEnum into Foo as a field member, it will crash at this point:

```c
enum FooEnum : uint32_t {
    Baz = 0
};

struct Foo 0x1000 {
    int blah;
    Foo foo_enum_before_i_found_the_enum;
};
```

**Comment by cursey** [comment]
Bug was in SdkGenny (fixed in https://github.com/cursey/sdkgenny/commit/f605a27557cac0f6765af2be80f7a98cc71847ab). Updated SdkGenny dependency in dea3b97ba8c05d044fc21adef2a3bd5f37eee152.
