### ISSUE TITLE
Invalid address when using module name

### ISSUE THREAD

**Issue by stdNullPtr** [cursey/regenny#23]
![image](https://github.com/user-attachments/assets/01e79e01-7d87-4e83-bc32-e5c906e051c2)

Very unintuitive and simply not working. It says invalid address even though I attached and it is valid I am looking at it in Reclass.
Also cant define a new type I have only Foo?

**Comment by praydog** [comment]
You need an offset. Type `<client.dll>+0`

Read the documentation if you have further issues at <https://praydog.github.io/regenny-book/>. If you have an error with your regenny file it should show up in the log at the bottom.
